# Master sollte
# das Kuerzel sein unter dem der Student seine DA bei uns als
# tar File abgibt, bei einem Bearbeiter die 4 Anfangsbuchstaben des Namens
# gefolgt vom Jahr der Bearbeitung

#MASTER := UNSET
MASTER := vp2012ss
